# Generated by Django 3.0.8 on 2020-08-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ListRouter',
        ),
    ]
