# Generated by Django 3.0.8 on 2020-08-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0002_auto_20200820_0932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListRouter',
            new_name='RouterList',
        ),
    ]
