# Generated by Django 3.0.8 on 2020-08-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0003_auto_20200820_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerlist',
            name='ip_address',
            field=models.CharField(max_length=24),
        ),
    ]
